services:
  prefect-server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: prefect-server
    command: prefect server start --host 0.0.0.0
    ports:
      - "4200:4200"
    networks:
      - prefect-net
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:4200/api/health || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 2s

  prefect-worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    container_name: prefect-worker
    volumes:
      - dbt_docs:/app/dbt_pipeline/target
    depends_on:
      prefect-server:
        condition: service_healthy
    env_file:
      - .env
    environment:
      PREFECT_API_URL: http://prefect-server:4200/api
    command: >
      bash -c "
      prefect work-pool create pipeline-pool --type process || true &&
      sleep 3 &&
      prefect --no-prompt deploy flows/terceirizados_pipeline.py:pipeline -n pipeline-terceirizados --pool pipeline-pool &&
      cd /app/dbt_pipeline &&
      dbt docs generate &&
      prefect worker start --pool pipeline-pool
      "
    networks:
      - prefect-net

  dbt-docs:
    image: nginx:alpine
    container_name: dbt-docs
    volumes:
      - dbt_docs:/usr/share/nginx/html:ro
    ports:
      - "4000:80"

  fast-api:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    container_name: fast-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: fastapi run code/main.py --port 8000
    networks:
      - prefect-net

networks:
  prefect-net:
    driver: bridge

volumes:
  dbt_docs: